index:
    path: /
    defaults: { _controller: 'App\Controller\IndexController::index' }

register:
    path: /register
    controller: App\Controller\IndexController::register

login:
    path: /login
    controller: App\Controller\IndexController::login


#app_lucky_number:
#    path: /lucky/number
#    controller: App\Controller\LuckyController::number